name: Build MiniGrok

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pablomk7/libctrpf:0.8.0

    steps:
      - uses: actions/checkout@v4

      - name: Build Plugin
        run: make

      - name: Upload 3GX
        uses: actions/upload-artifact@v4
        with:
          name: MiniGrok-3gx
          path: |
            MiniGrok.3gx
            MiniGrok.elf
          if-no-files-found: error
